[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 20_000
gas_reports = ["*"]

[etherscan]
bsc = { key = "${BSCSCAN_KEY}", url = "https://api.bscscan.com" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
